# Generated by Django 2.1.7 on 2019-03-28 03:18

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190327_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=unixtimestampfield.fields.UnixTimeStampField(),
        ),
    ]
